app:
    port: '3000'
    host: 'https://www.xxx.com'
    prefix: /api
    free_days: '7'
verify:
    maxip: '36'
    maxphone: '6'
mysql:
    host: 127.0.0.1
    user: root
    password: 786699892qing
    database: doodoo2
    port: '3306'
    charset: utf8mb4
redis:
    host: 127.0.0.1
    port: '6379'
    prefix: 'doodooke:'
qiniu:
    accesskey: xxx
    secretkey: xxx
    bucket: doodooke
    domain: 'http://img.xxx.com'
page:
    size: '20'
jwt:
    secret: 978c45d1-0359-4a08-899e-86304ffa9491
    expiresin: 7 days
    admin_secret: 2b121174-7893-49c8-91f4-9f92ff576e9a
    admin_expiresin: 7 days
open:
    appid: xxx
    appsecret: xxx
    token: xxx
    encodingaeskey: xxx
    domain: 'https://api.xxx.com'
wx:
    appid: xxx
    appsecret: xxx
    token: xxx
    encodingaeskey: xxx
alisms:
    type: '1'
    appkey: xxx
    appsecret: xxx
    free_sign_name: xxx
    template_code: xxx
lbs:
    amap_key: xxx
