version: "2"
services:
  redis:
    image: "redis"
    restart: "always"
    cpu_shares: 30
    mem_limit: "4M"
    # ports:
    #   - "6379:6379"
    volumes:
      - "./docker/redis/log:/var/log/redis"
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    image: "mysql:8.0.19"
    restart: "always"
    cpu_shares: 60
    mem_limit: "1G"
    # ports:
    #   - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=xxx"
    volumes:
      - "./docker/mysql/conf:/etc/mysql/conf.d"
      - "./docker/mysql/data:/var/lib/mysql"
      - "./docker/mysql/log:/var/log/mysql"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    restart: "always"
    cpu_shares: 10
    mem_limit: "200M"
    ports:
      - "8080:80"
    links:
      - "mysql:db"
    depends_on:
      - "mysql"
    environment:
      - "PMA_PORT=3306"
      - "UPLOAD_LIMIT=4G"
  doodooke:
    image: "einsqing/doodooke"
    restart: "always"
    ports:
      - "3000:3000"
    links:
      - "mysql:mysql"
      - "redis:redis"
    depends_on:
      - "mysql"
      - "redis"